tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "anyenv"
brew "bat"
brew "exa"
brew "docker", link: false
brew "docker-compose", link: false
brew "fd"
brew "fzf"
brew "ghq"
brew "git"
brew "git-lfs"
brew "jq"
brew "lazygit"
brew "nvim"
brew "neovim"
brew "tmux"
brew "peco"
brew "zsh"

cask "1password"
cask "appcleaner"
cask "discord"
cask "docker"
cask "hyper"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "slack"
cask "skitch"
cask "visual-studio-code"
cask "tickeys"
