[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = '''
  let g:coc_global_extensions = [
    \'coc-word',
    \'coc-json',
    \'coc-tsserver',
    \'coc-java',
  \]
'''
# hook_source = 'call config#init#coc#hook_source()'
